version: "2"
services:
  rethink:
    image: rethinkdb:2.3
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"

  collector:
    image: passy/disruption-tracker:v0.2.0.0
    depends_on:
      - rethink
    command: --hostname rethink --verbose collectd --die-on-error
    restart: unless-stopped

  bot:
    image: passy/tube-bot:v0.1.10
    depends_on:
      - rethink
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    ports:
      - "127.0.0.1:5000:5000"

  roundel:
    image: passy/tube-roundel:v0.1.0.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
