version: "2"
services:
  rethink:
    image: rethinkdb:2.3
    restart: unless-stopped
    ports:
      - "8080:8080"

  collector:
    image: passy/disruption-tracker:v0.0.2.4
    depends_on:
      - rethink
    command: --hostname rethink collectd
    restart: unless-stopped

  bot:
    image: passy/disruption-fb-bot:v0.0.2
    depends_on:
      - rethink
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"
